### ISSUE TITLE
Reading .prof files created by gperftools

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/gprofiler#1]
currently requires [`pprof`](https://github.com/google/pprof), a Go program. Need to do one of the following:

1. Parse the textual output of `pprof`
1. Call Go from R via [cgo](https://golang.org/cmd/cgo/#hdr-C_references_to_Go)
1. Rebuild the parser for the profiler output in R
1. Build a reader for the [profiler data](https://gperftools.github.io/gperftools/cpuprofile-fileformat.html)

A first implementation will focus on the first option and require a compatible version of `pprof` that can be found by the package.

**Comment by krlmlr** [comment]
pprof also parses the "legacy format" that might be replaced with a protobuf-based format. Options 3 and 4 are out of scope, it feels better to embed the pprof Go library (option 2).

Resources:

- https://romain.rbind.io/blog/2017/05/14/calling-go-from-r/
- https://romain.rbind.io/blog/2017/06/09/go-packages-in-r-packages/
- https://romain.rbind.io/blog/2017/06/10/using-go-strings-in-r/
- https://romain.rbind.io/blog/2017/07/03/go-slices/

Thanks @romainfrancois!

**Comment by romainfrancois** [comment]
Cool. At some point I need to commit to do some proper R/go bridge. 
These articles just scratch the surface. Knowing there are potential use cases beyond "that would be cool" does help.

**Comment by krlmlr** [comment]
Unfortunately, at this point pprof doesn't export its symbolizer API. We'd need to fork the project and add our own API, or examine existing forks. At this point the easiest route seems to be 1), but we still can/should build the executable ourselves.

**Comment by krlmlr** [comment]
pprof issue: https://github.com/google/pprof/issues/281
